version: 0.2

phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_lts.x | bash -
      - apt install -y nodejs
      - npm install -g next
  pre_build:
    commands:
      - npm install
  build:
    commands:
    - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: out
  